### ISSUE TITLE
Can't import the package 

### ISSUE THREAD

**Issue by PierreLouisPAUGAM** [nicollasricas/unity-streamdeck#4]
## Expected Behavior

When selecting the .unitypackage in the Finder it should add the package to my Unity Project.

## Actual Behavior

![Capture d’écran 2021-06-02 à 14 26 49](https://user-images.githubusercontent.com/58030198/120479998-df1ede00-c3ae-11eb-98f6-9e31113a15ba.png)

## Steps to Reproduce

The exact first two steps from the "Getting Started" section.
I reproduces it with multiple project including a blank one.

I don't have any issue with other packages.

## Specifications

- Unity Version: 2020.3.9f1
- Platform (Windows or Mac): M1 MacBook Pro / macOS Big Sur 11.3.1

**Comment by nicollasricas** [comment]
Hi,

Does the assets/plugins folder exist? If not try to create before import. Never seen this error before.

The only thing I could think of is the libraries not be able to import, but it should as they are tagged as any OS and mono compatible.

Could you try to import this package? I exported directly from Unity Editor instead of the generated by CI.

[UnityStreamDeckExportedByEditor.zip](https://github.com/nicollasricas/unity-streamdeck/files/6585554/UnityStreamDeckExportedByEditor.zip)

**Comment by PierreLouisPAUGAM** [comment]
Hi and thanks for your answer.

The "ProjectRepo/Assets/Plugins" didn't exist so I created it but the end result was the same.

I downloaded "UnityStreamDeckExportedByEditor.zip" but it doesn't contain any .unitypackage file. Is it another way to import packages ?

![Capture d’écran 2021-06-02 à 17 28 00](https://user-images.githubusercontent.com/58030198/120508332-e999a180-c3c7-11eb-88d6-c8a73f498d40.png)

**Comment by nicollasricas** [comment]
Inside the zip file, there's a .unitypackage file that you can import.

Extract the zip anywhere, go to the Unity Editor, right-click on the Assets folder, import package and select that file.

**Comment by PierreLouisPAUGAM** [comment]
Ok, when I tried to unzip it with the built-in macOS solution it also unzipped the .unitypackage at the same time hence the issue. I downloaded a third party software "The Unarchiver" and it worked.

I was able to import the package in my Unity project that way. Thanks a lot for your time, I'd star your repo if it was not already done :)

![Capture d’écran 2021-06-02 à 17 55 27](https://user-images.githubusercontent.com/58030198/120512518-bbb65c00-c3cb-11eb-9005-553015b853d6.png)

**Comment by nicollasricas** [comment]
If you keep the version I exported manually over the version from GitHub releases you can delete the test.txt file that is inside: Assets/Plugins/StreamDeck/Editor/

![image](https://user-images.githubusercontent.com/7860985/120527091-f1494e00-c3a7-11eb-93cd-ea759f98d215.png)

> ![Capture d’écran 2021-06-02 à 17 28 00](https://user-images.githubusercontent.com/58030198/120508332-e999a180-c3c7-11eb-88d6-c8a73f498d40.png)

For some reason, the OS was identifying the .unitypackage file as a folder.

> I was able to import the package in my Unity project that way. Thanks a lot for your time, I'd star your repo if it was not already done :)

Thank you, I hope it helps.
