### ISSUE TITLE
Stream Deck disconnected when I add a Unity tile to the layout.

### ISSUE THREAD

**Issue by PierreLouisPAUGAM** [nicollasricas/unity-streamdeck#5]
Hello again,

## Expected Behavior

After the plugin's successful connection, when adding a Unity tile from your Stream Deck add-on like this : 

![Capture d’écran 2021-06-02 à 20 29 50](https://user-images.githubusercontent.com/58030198/120533898-8583d700-c3e1-11eb-911a-5a13f5b09b04.png)

The Unity plugin should stay connected to the Stream Deck

## Actual Behavior

If I add the tile after launching the Unity project, the plugin disconnects from the Stream Deck.
If I add the tile before opening the project, the plugin connection fails at launch.

In either case this is the error I get : 

![Capture d’écran 2021-06-02 à 20 34 03](https://user-images.githubusercontent.com/58030198/120534507-34281780-c3e2-11eb-84ab-d6bb5f69211b.png)

## Specifications

- Unity Version: 2020.3.9f1
- Platform (Windows or Mac): M1 MacBook Pro / Big Sur 11.3.1

Thanks in advance for your time.

**Comment by nicollasricas** [comment]
Hey,

Please attach the pluginlog.log file here.

Location:
`~/Library/Application Support/com.elgato.StreamDeck/Plugins/com.nicollasr.streamdeckunity.mac.sdPlugin/pluginlog.log`
