### ISSUE TITLE
Unable to toggle Scene/Game view

### ISSUE THREAD

**Issue by David-Everlasting-Media** [nicollasricas/unity-streamdeck#6]
## Expected Behavior
Toggles between Game and Scene view.
Please describe the behavior you are expecting

## Actual Behavior
![image](https://user-images.githubusercontent.com/59494766/140691563-d1976a84-5ab2-48a6-9153-dbcd888fbc08.png)

What is the actual behavior?
![image](https://user-images.githubusercontent.com/59494766/140691563-d1976a84-5ab2-48a6-9153-dbcd888fbc08.png)
## Steps to Reproduce

1. Install Unity Editor v2020.3.20f1
2. Install StreamDeck plugin
3. Add button to any Profile
4. Attempt to toggle to/from Scene/Game views. 

## Specifications

- Unity Version: v2020.3.20f1
- Platform (Windows or Mac): Win 10 Pro x64

## Failure Logs

> Windows: %appdata%/Elgato/StreamDeck/Plugins/com.nicollasr.streamdeckunity.sdPlugin/pluginlog.log

> Mac: ~/Library/Application Support/com.elgato.StreamDeck/Plugins/com.nicollasr.streamdeckunity.mac.sdPlugin/pluginlog.log

Please include any relevant log snippets or files here.

**Comment by nicollasricas** [comment]
Hey,

I've released an update fixing the issue, don't forget to re-import the [package](github.com/nicollasricas/unity-streamdeck/releases/latest) into your projects.

I will add the package to the unity asset store later in making this process faster and easier, but it won't happen in the next few days.

Thanks for reporting.
