### ISSUE TITLE
AddComponent not working

### ISSUE THREAD

**Issue by Mecze** [nicollasricas/unity-streamdeck#9]
Hi!
AddComponent is not currently working.
I work a lot with interface, so I'm trying Adding Image component to an Object via StreamDeck and is not working.

.Net is set at 4.x

The plugin connects, no problem.

![image](https://user-images.githubusercontent.com/21218454/149125343-25f76565-d744-4bc7-9f8d-b5aac2facfd6.png)

**Comment by nicollasricas** [comment]
Hey,

I've released an update fixing the issue, don't forget to re-import the [package](https://www.github.com/nicollasricas/unity-streamdeck/releases/latest) into your projects.

If not working, go to settings enable debugging, which will show every cached component name. Try to find your Image component full name and use that name.

Let me know if it works.

Thanks for reporting.

**Comment by LuukDomhof** [comment]
I've tested out adding components, and it seems to work just fine :)
